package de.chloedev.cdnbot.discord.command.impl;

import de.chloedev.cdnbot.discord.command.Command;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.channel.unions.MessageChannelUnion;

import java.net.URI;
import java.net.URL;
import java.nio.charset.StandardCharsets;

public class FabricDocsCommand implements Command {

    @Override
    public String getName() {
        return "fabdoc";
    }

    @Override
    public void onReceive(String[] args, MessageChannelUnion channel, User author) {
        if (args.length != 3) {
            channel.sendMessage("Invalid Arguments.").queue();
        }
        if (args[0].equals("getDoc")) {
            try {
                URL url = new URI("https://maven.fabricmc.net/docs/yarn-" + args[1] + "+build." + 1 + "/" + args[2] + ".html").toURL();
                String response = new String(url.openStream().readAllBytes(), StandardCharsets.UTF_8).substring(0, 1980);
                channel.sendMessage(response.contains("Generated by javadoc") ? url.toString() : "No Doc found...").queue();
            } catch (Exception e) {
                channel.sendMessage("No Doc found...").queue();
            }
        }
    }
}
